version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
